name = "Most of Quilt"
author = "RyzechDev"
version = "1.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1c142acd73b15542bb549c0e3063af772ba83f0a22c28bb4e2855b44cabfc35"

[versions]
minecraft = "1.19.2"
quilt = "0.19.1-beta.1"
